# Change these first
owner: chik4ge-homelab # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Argo CD
    url: https://argocd.chik4ge.me
    headers:
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
  - name: Proxmox VE
    url: https://proxmox.chik4ge.me
    headers:
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
  - name: Longhorn
    url: https://longhorn.chik4ge.me
    headers:
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
  - name: Grafana
    url: https://grafana.chik4ge.me
    headers:
      - "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET"
  - name: CUBE cocricot Server
    check: "tcp-ping"
    url: $CUBE_COCRICOT_SERVER_URL
    port: 25565
  - name: CUBE cocricot Map
    url: $CUBE_COCRICOT_MAP_URL
  - name: CUBE MiniaTuria Server
    check: "tcp-ping"
    url: $CUBE_MINIATURIA_SERVER_URL
    port: 25565
  - name: CUBE MiniaTuria Map
    url: $CUBE_MINIATURIA_MAP_URL
    
assignees:
  - chik4ge
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.chik4ge.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
